# Generated by Django 4.0 on 2024-02-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksites',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksites',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='worksite_images/'),
        ),
        migrations.AlterField(
            model_name='worksites',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='worksites',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='worksites',
            name='net_worth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
