# Generated by Django 4.0 on 2024-01-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksites',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
