# Generated by Django 4.0 on 2024-02-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0004_alter_collabworksites_worksite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksites',
            name='type',
        ),
    ]
