# Generated by Django 4.0 on 2024-02-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0006_alter_worksitescategories_worksite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistworksites',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='checklistworksites',
            name='worksites',
        ),
        migrations.RenameField(
            model_name='worksites',
            old_name='is_open',
            new_name='is_visible',
        ),
        migrations.AddField(
            model_name='collabworksites',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collabworksites',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksites',
            name='codice_CIG',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='worksites',
            name='codice_CUP',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='worksites',
            name='codice_commessa',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='worksites',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksites',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksites',
            name='percentage_worth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksites',
            name='status',
            field=models.CharField(choices=[('APERTO', 'MESSAGE'), ('SOSPESO', 'UPDATE'), ('CHIUSA', 'UPDATE')], default='APERTO', max_length=20),
        ),
        migrations.DeleteModel(
            name='CheckList',
        ),
        migrations.DeleteModel(
            name='CheckListWorksites',
        ),
    ]
