# Generated by Django 4.0 on 2024-02-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0008_alter_collabworksites_date_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoglioParticella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foglio', models.IntegerField()),
                ('particella', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorksitesFoglioParticella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foglio_particella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksites.foglioparticella')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksites.worksites')),
            ],
        ),
    ]
