# Generated by Django 4.0 on 2024-02-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0009_foglioparticella_worksitesfoglioparticella'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksitesfoglioparticella',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foglio_particelle', to='worksites.worksites'),
        ),
    ]
