# Generated by Django 4.0 on 2024-02-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('worksites', '0010_alter_worksitesfoglioparticella_worksite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabworksites',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collabworksites', to='accounts.profile'),
        ),
    ]
