# Generated by Django 4.0 on 2024-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0011_alter_collabworksites_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foglioparticella',
            name='foglio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foglioparticella',
            name='particella',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
