# Generated by Django 4.0 on 2024-02-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0012_alter_foglioparticella_foglio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksites',
            name='codice_CIG',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksites',
            name='codice_CUP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worksites',
            name='codice_commessa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
