# Generated by Django 4.0 on 2024-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0013_alter_worksites_codice_cig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksites',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='worksitesprofile',
            name='approved',
            field=models.BooleanField(default=False),
        )
    ]
