# Generated by Django 4.0 on 2024-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0014_worksites_is_active'),
    ]

    operations = [

    ]
