# Generated by Django 4.0 on 2024-02-26 14:33

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0015_worksites_approved'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('order', models.IntegerField()),
            ],
        )
    ]
