# Generated by Django 4.0 on 2024-02-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0016_status_worksitesstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabworksites',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
