# Generated by Django 4.0 on 2024-03-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0017_collabworksites_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksitesstatus',
            name='status',
        ),
    ]
