# Generated by Django 4.0 on 2024-03-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0018_remove_worksitesstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksitesstatus',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worksites.status'),
        ),
    ]
