# Generated by Django 4.0 on 2024-03-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0019_worksitesstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksitesstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksites.status'),
        ),
    ]
