# Generated by Django 4.0 on 2024-03-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0020_alter_worksitesstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksitesstatus',
            name='worksite',
        ),
    ]
