# Generated by Django 4.0 on 2024-03-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0021_remove_worksitesstatus_worksite'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksitesstatus',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worksites.worksites'),
        ),
    ]
