# Generated by Django 4.0 on 2024-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0023_alter_worksitesstatus_worksite'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksitesstatus',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
