# Generated by Django 4.0 on 2024-03-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0024_worksitesstatus_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksitesstatus',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
