# Generated by Django 4.0 on 2024-03-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0026_worksitesstatus_active_alter_worksitesstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksitesstatus',
            name='is_current',
        ),
    ]
