# Generated by Django 4.0 on 2024-03-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('worksites', '0027_remove_worksitesstatus_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabWorksitesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksites.worksites')),
            ],
        ),
    ]
