# Generated by Django 4.0 on 2024-03-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0028_collabworksitesorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabworksites',
            name='order',
        ),
    ]
