# Generated by Django 4.0 on 2024-03-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0029_remove_collabworksites_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabworksitesorder',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
