# Generated by Django 4.0 on 2024-03-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('worksites', '0030_collabworksitesorder_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabworksitesorder',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collabworksitesOrder', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='collabworksitesorder',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborationsOrder', to='worksites.worksites'),
        ),
    ]
