# Generated by Django 4.0 on 2024-03-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0031_alter_collabworksitesorder_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foglioparticella',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
