# Generated by Django 4.0 on 2024-03-13 15:19

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0032_foglioparticella_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='foglioparticella',
            managers=[
                ('oggetti_attivi', django.db.models.manager.Manager()),
            ],
        ),
    ]
