# Generated by Django 4.0 on 2024-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0033_alter_foglioparticella_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksites',
            name='status',
            field=models.CharField(choices=[('APERTO', 'APERTO'), ('SOSPESO', 'SOSPESO'), ('CHIUSO', 'CHIUSO')], default='APERTO', max_length=20),
        ),
    ]
