Table auth_profile {
  id integer [pk]
  user_id integer [unique]
  image varchar
  first_name varchar(100)
  last_name varchar(100)
  mobile_number varchar(100)
  token varchar(150)
  is_active boolean
  email varchar(100) [unique]
  date timestamp
  date_update timestamp
  type varchar(7) [note: 'Choices are USER, TECNICI, STAFF']
}

Table boards_read {
  id integer [pk]
  profile_id integer [ref: > auth_profile.id]
  board_id integer [ref: > boards_boards.id]
  date timestamp
}

Table boards_attachment {
  id integer [pk]
  board_id integer [ref: > boards_boards.id]
  survey_id integer [ref: > survey_survey.id]
  attachment_link varchar
  type varchar(7) [note: 'Choices are DOCUMENT, IMAGE, SURVEY']
  date timestamp
}

Table boards_boards {
  id integer [pk]
  worksite_id integer [ref: > worksites_workstite.id]
  apartment_id integer [ref: > worksites_apartments.id]
  image varchar
  title varchar(250)
  body text
  author varchar(150)
  date timestamp
  date_update timestamp
  recipients int
  type varchar(7) [note: 'Choices are MESSAGE, UPDATE']
}

Table boards_boardsAnswer{
  id integer [pk]
  boards_id integer [ref: > boards_boards.id]
  profile integer [ref: > auth_profile.id]
  date timestamp
  choiches integer [ref: > survey_questionChoiches.id]
}

Table survey_survey {
  id integer [pk]
  name varchar(100)
}

Table survey_question {
  id integer [pk]
  survey_id integer [ref: > survey_survey.id]
  name varchar(100)
}

Table survey_questionChoiches {
  id integer [pk]
  questionarie_id integer [ref: > survey_question.id]
  name varchar(100)
}

Table worksites_apartments {
  id integer [pk]
  worksite_id integer [ref: > worksites_workstite.id]
  foglio int
  particella int
  sub int
  interno int
  surface varchar(100)
  note varchar(100)
  owner varchar(100)
  owner_phone varchar(100)
  owner_email varchar(100)
  owner_cf varchar(100)
  link varchar(100)
  date timestamp
  date_update timestamp
}

Table worksites_workstite {
  id integer [pk]
  image varchar
  name varchar(100)
  address varchar(100)
  lat decimal(10)
  lon decimal(10)
  is_visible boolean
  satus varchar(7) [note: 'Choices are APERTO, SOSPESO, CHIUSO']
  net_worth float
  percentage_worth float 
  financier int [ref: > worksites_financier.id]
  contractor_id int [ref: > worksites_contractor.id]
  link varchar(100)
  date timestamp
  date_update timestamp
  codice_commessa string [pk]
  codice_CIG string
  codice_CUP string 
  date_start timestamp
  date_end timestamp
}

Table worksites_workstite_r_profile{
    id integer [pk]
    profile_id integer [ref: > auth_profile.id]
    worksite_id integer [ref: > worksites_workstite.id]
}

Table worksites_workstite_r_collaborator {
  id integer [pk]
  profile_id integer [ref: > auth_profile.id]
  worksite_id integer [ref: > worksites_workstite.id]
  role varchar(150) 
  order integer
  data_inizio integer
  data_fine integer
}

Table worksites_client_r_apartments {
  id integer [pk]
  profile_id integer [ref: > auth_profile.id]
  apartment_id integer [ref: > worksites_apartments.id]
  is_active boolean
}

table worksites_categories {
  id integer [pk]
  name varchar(150)
}

Table worksites_worksites_r_categories{
    id integer [pk]
    category_id integer [ref: > worksites_categories.id]
    worksite_id integer [ref: > worksites_workstite.id]
}

table worksites_checklist{
  id integer [pk]
  name varchar(100)
}

table worksites_checklist_r_worksite {
  id integer [pk]
  worksites_id int [ref: > worksites_workstite.id]
  checklist_id int [ref: > worksites_checklist.id]
  apartments_id int [ref: > worksites_apartments.id]
  date timestamp
  order int
  is_done boolean
}

Table worksites_financier {
  id integer [pk]
  name varchar(150)
}

Table worksites_contractor {
  id integer [pk]
  name varchar(150)
}