# Generated by Django 4.0 on 2024-01-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
