# Generated by Django 4.0 on 2024-02-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worksites', '0001_initial'),
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksites.worksites'),
        ),
    ]
