# Generated by Django 4.0 on 2024-02-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0007_remove_checklistworksites_checklist_and_more'),
        ('apartments', '0003_clientapartments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CheckListWorksites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField()),
                ('is_done', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartments')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.checklist')),
                ('worksites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksites.worksites')),
            ],
        ),
    ]
