# Generated by Django 4.0 on 2024-02-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0009_foglioparticella_worksitesfoglioparticella'),
        ('apartments', '0004_checklist_checklistworksites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartments',
            old_name='foglio',
            new_name='floor',
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='particella',
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='surface',
        ),
        migrations.CreateModel(
            name='ApartmentSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.IntegerField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartments')),
                ('foglio_particella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksites.foglioparticella')),
            ],
        ),
    ]
