# Generated by Django 4.0 on 2024-02-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_rename_foglio_apartments_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsub',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='apartments.apartments'),
        ),
    ]
