# Generated by Django 4.0 on 2024-02-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_alter_apartmentsub_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='floor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
