# Generated by Django 4.0 on 2024-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_alter_apartments_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsub',
            name='sub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
