# Generated by Django 4.0 on 2024-02-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_alter_apartmentsub_foglio_particella'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
