# Generated by Django 4.0 on 2024-03-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_apartments_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsub',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
