# Generated by Django 4.0 on 2024-03-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_email'),
        ('apartments', '0012_apartmentsub_date_apartmentsub_date_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('jwt_token_new', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartments')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
