# Generated by Django 4.0 on 2024-03-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0013_apartmentaccesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentaccesscode',
            name='qrcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
