# Generated by Django 4.0 on 2024-07-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0016_room_wbs_wbsroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbs',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
