# Generated by Django 4.0 on 2024-07-07 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0034_alter_worksites_status'),
        ('apartments', '0017_wbs_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBSWorksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.wbs')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksites.worksites')),
            ],
        ),
    ]
