# Generated by Django 4.0 on 2024-07-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0018_wbsworksite'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbsworksite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
