# Generated by Django 4.0 on 2024-03-26 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_need_change_password'),
        ('worksites', '0034_alter_worksites_status'),
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='directory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worksites.worksites'),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('name', 'parent'), ('name', 'worksite')},
        ),
    ]
