# Generated by Django 4.0 on 2024-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_directory_created_by_directory_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
