# Generated by Django 4.0 on 2024-03-27 14:14

from django.db import migrations, models
import falone.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0003_file_date_file_extension_file_mime_type_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=falone.storage_backends.PrivateMediaStorage(), upload_to='files/'),
        ),
    ]
 