# Generated by Django 4.0 on 2024-04-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0015_alter_apartmentaccesscode_apartment'),
        ('file_manager', '0004_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.apartments'),
        ),
    ]
 