# Generated by Django 4.0 on 2024-07-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0007_directory_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='type',
            field=models.CharField(blank=True, choices=[('WORKSITE', 'WORKSITE'), ('APARTMENT', 'APARTMENT'), ('ROOM', 'ROOM')], max_length=10, null=True),
        ),
    ]
