# Generated by Django 4.0 on 2024-07-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0008_directory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='type',
            field=models.CharField(blank=True, choices=[('WORKSITE', 'WORKSITE'), ('APARTMENT', 'APARTMENT'), ('ROOM', 'ROOM'), ('WBS', 'WBS')], max_length=10, null=True),
        ),
    ]
