# Generated by Django 4.0 on 2024-07-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0018_wbsworksite'),
        ('file_manager', '0009_alter_directory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.room'),
        ),
    ]
