# Generated by Django 4.0 on 2024-03-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firebase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('additional_params', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(default=dict)),
                ('consent', models.BooleanField(default=False)),
                ('last_access', models.DateTimeField(auto_now_add=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('userId', models.CharField(blank=True, max_length=500, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
    ]
