# Generated by Django 4.0 on 2024-03-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='need_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
