# Generated by Django 4.0 on 2024-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_privacy_privacyacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_visible',
            field=models.BooleanField(default=True),
        ),
    ]
