# Generated by Django 4.0 on 2024-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_phone_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='need_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
