# Generated by Django 3.2 on 2022-11-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20221107_1600'),
        ('accounts', '0017_cantina'),
    ]

    operations = [
    ]
