# Generated by Django 3.2 on 2022-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20221108_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admission',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='admission'),
        ),
    ]
