# Generated by Django 3.2 on 2022-12-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20221213_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='username',
            new_name='user',
        ),
    ]
