# Generated by Django 3.2 on 2022-12-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20221222_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('vendor', 'vendor')], default='vendor', max_length=13, null=True),
        ),
    ]
