# Generated by Django 3.2 on 2023-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admission',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='admission'),
        ),
    ]
