# Generated by Django 3.2 on 2023-02-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_profile_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='vendor_profile',
        ),
        migrations.DeleteModel(
            name='Cantina',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='vendor_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='blance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='piva',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recommended_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referrals',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='registered_office',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='requested',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unicode',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
