# Generated by Django 3.2 on 2023-02-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20230213_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
