# Generated by Django 4.0 on 2024-01-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('USER', 'USER'), ('TECNICI', 'TECNICI'), ('STAFF', 'STAFF')], default='USER', max_length=7),
        ),
    ]
