# Generated by Django 4.0 on 2024-01-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worksites', '0001_initial'),
        ('accounts', '0035_collaborators'),
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabWorksites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collabworksites_collaborators', to='accounts.collaborators')),
                ('worksite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collabworksites_worksites', to='worksites.worksites')),
            ],
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='worksite_pic/')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.apartments')),
                ('worksite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worksites.worksites')),
            ],
        ),
    ]
