# Generated by Django 4.0 on 2024-02-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_link', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('DOCUMENT', 'DOCUMENT'), ('IMAGE', 'IMAGE')], default='IMAGE', max_length=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='board_images/')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('recipients', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('MESSAGE', 'MESSAGE'), ('UPDATE', 'UPDATE')], default='MESSAGE', max_length=7)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartments')),
            ],
        ),
    ]
