# Generated by Django 4.0 on 2024-01-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
