# Generated by Django 4.0 on 2024-02-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worksites', '0001_initial'),
        ('accounts', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksites.worksites'),
        ),
        migrations.AddField(
            model_name='boardread',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.boards'),
        ),
        migrations.AddField(
            model_name='boardread',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='boardattachments',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.boards'),
        ),
    ]
