# Generated by Django 4.0 on 2024-01-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boards_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='name',
        ),
    ]
