# Generated by Django 4.0 on 2024-02-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0008_alter_collabworksites_date_start'),
        ('apartments', '0004_checklist_checklistworksites'),
        ('accounts', '0001_initial'),
        ('board', '0003_survey_alter_boardattachments_attachment_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.survey')),
            ],
        ),
        migrations.RemoveField(
            model_name='boards',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='boards',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='boards',
            name='worksite',
        ),
        migrations.CreateModel(
            name='SurveyQuestionChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.surveyquestion')),
            ],
        ),
        migrations.CreateModel(
            name='BoardsRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('APARTMENT', 'APARTMENT'), ('WORKSITE', 'WORKSITE'), ('PROFILE', 'PROFILE')], default='WORKSITE', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartments')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.boards')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('worksites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksites.worksites')),
            ],
        ),
    ]
