# Generated by Django 4.0 on 2024-02-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksites', '0008_alter_collabworksites_date_start'),
        ('accounts', '0001_initial'),
        ('apartments', '0004_checklist_checklistworksites'),
        ('board', '0004_surveyquestion_remove_boards_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsrecipient',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.apartments'),
        ),
        migrations.AlterField(
            model_name='boardsrecipient',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='boardsrecipient',
            name='worksites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worksites.worksites'),
        ),
    ]
