# Generated by Django 4.0 on 2024-02-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_boardsrecipient_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardsrecipient',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='board.boards'),
        ),
    ]
