# Generated by Django 4.0 on 2024-02-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_boardsrecipient_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='board_images/'),
        ),
    ]
